# Assignment

<font face='georgia'>
    
   <h4><strong>What does tf-idf mean?</strong></h4>

   <p>    
Tf-idf stands for <em>term frequency-inverse document frequency</em>, and the tf-idf weight is a weight often used in information retrieval and text mining. This weight is a statistical measure used to evaluate how important a word is to a document in a collection or corpus. The importance increases proportionally to the number of times a word appears in the document but is offset by the frequency of the word in the corpus. Variations of the tf-idf weighting scheme are often used by search engines as a central tool in scoring and ranking a document's relevance given a user query.
</p>
    
   <p>
One of the simplest ranking functions is computed by summing the tf-idf for each query term; many more sophisticated ranking functions are variants of this simple model.
</p>
    
   <p>
Tf-idf can be successfully used for stop-words filtering in various subject fields including text summarization and classification.
</p>
    
</font>

<font face='georgia'>
    <h4><strong>How to Compute:</strong></h4>

Typically, the tf-idf weight is composed by two terms: the first computes the normalized Term Frequency (TF), aka. the number of times a word appears in a document, divided by the total number of words in that document; the second term is the Inverse Document Frequency (IDF), computed as the logarithm of the number of the documents in the corpus divided by the number of documents where the specific term appears.

 <ul>
    <li>
<strong>TF:</strong> Term Frequency, which measures how frequently a term occurs in a document. Since every document is different in length, it is possible that a term would appear much more times in long documents than shorter ones. Thus, the term frequency is often divided by the document length (aka. the total number of terms in the document) as a way of normalization: <br>

$TF(t) = \frac{\text{Number of times term t appears in a document}}{\text{Total number of terms in the document}}.$
</li>
<li>
<strong>IDF:</strong> Inverse Document Frequency, which measures how important a term is. While computing TF, all terms are considered equally important. However it is known that certain terms, such as "is", "of", and "that", may appear a lot of times but have little importance. Thus we need to weigh down the frequent terms while scale up the rare ones, by computing the following: <br>

$IDF(t) = \log_{e}\frac{\text{Total  number of documents}} {\text{Number of documents with term t in it}}.$
for numerical stabiltiy we will be changing this formula little bit
$IDF(t) = \log_{e}\frac{\text{Total  number of documents}} {\text{Number of documents with term t in it}+1}.$
</li>
</ul>

<br>
<h4><strong>Example</strong></h4>
<p>

Consider a document containing 100 words wherein the word cat appears 3 times. The term frequency (i.e., tf) for cat is then (3 / 100) = 0.03. Now, assume we have 10 million documents and the word cat appears in one thousand of these. Then, the inverse document frequency (i.e., idf) is calculated as log(10,000,000 / 1,000) = 4. Thus, the Tf-idf weight is the product of these quantities: 0.03 * 4 = 0.12.
</p>
</font>

## Task-1

<font face='georgia'>
    <h4><strong>1. Build a TFIDF Vectorizer & compare its results with Sklearn:</strong></h4>

<ul>
    <li> As a part of this task you will be implementing TFIDF vectorizer on a collection of text documents.</li>
    <br>
    <li> You should compare the results of your own implementation of TFIDF vectorizer with that of sklearns implemenation TFIDF vectorizer.</li>
    <br>
    <li> Sklearn does few more tweaks in the implementation of its version of TFIDF vectorizer, so to replicate the exact results you would need to add following things to your custom implementation of tfidf vectorizer:
       <ol>
        <li> Sklearn has its vocabulary generated from idf sroted in alphabetical order</li>
        <li> Sklearn formula of idf is different from the standard textbook formula. Here the constant <strong>"1"</strong> is added to the numerator and denominator of the idf as if an extra document was seen containing every term in the collection exactly once, which prevents zero divisions.
            
 $IDF(t) = 1+\log_{e}\frac{1\text{ }+\text{ Total  number of documents in collection}} {1+\text{Number of documents with term t in it}}.$
        </li>
        <li> Sklearn applies L2-normalization on its output matrix.</li>
        <li> The final output of sklearn tfidf vectorizer is a sparse matrix.</li>
    </ol>
    <br>
    <li>Steps to approach this task:
    <ol>
        <li> You would have to write both fit and transform methods for your custom implementation of tfidf vectorizer.</li>
        <li> Print out the alphabetically sorted voacb after you fit your data and check if its the same as that of the feature names from sklearn tfidf vectorizer. </li>
        <li> Print out the idf values from your implementation and check if its the same as that of sklearns tfidf vectorizer idf values. </li>
        <li> Once you get your voacb and idf values to be same as that of sklearns implementation of tfidf vectorizer, proceed to the below steps. </li>
        <li> Make sure the output of your implementation is a sparse matrix. Before generating the final output, you need to normalize your sparse matrix using L2 normalization. You can refer to this link https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.normalize.html </li>
        <li> After completing the above steps, print the output of your custom implementation and compare it with sklearns implementation of tfidf vectorizer.</li>
        <li> To check the output of a single document in your collection of documents,  you can convert the sparse matrix related only to that document into dense matrix and print it.</li>
        </ol>
    </li>
    <br>
   </ul>

  <p> <font color="#e60000"><strong>Note-1: </strong></font> All the necessary outputs of sklearns tfidf vectorizer have been provided as reference in this notebook, you can compare your outputs as mentioned in the above steps, with these outputs.<br>
   <font color="#e60000"><strong>Note-2: </strong></font> The output of your custom implementation and that of sklearns implementation would match only with the collection of document strings provided to you as reference in this notebook. It would not match for strings that contain capital letters or punctuations, etc, because sklearn version of tfidf vectorizer deals with such strings in a different way. To know further details about how sklearn tfidf vectorizer works with such string, you can always refer to its official documentation.<br>
   <font color="#e60000"><strong>Note-3: </strong></font> During this task, it would be helpful for you to debug the code you write with print statements wherever necessary. But when you are finally submitting the assignment, make sure your code is readable and try not to print things which are not part of this task.
    </p>

### Corpus

In [541]:
## SkLearn# Collection of string documents

corpus = [
     'this is the first document',
     'this document is the second document',
     'and this is the third one',
     'is this the first document',
]

### SkLearn Implementation

In [542]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
vectorizer.fit(corpus)
skl_output = vectorizer.transform(corpus)

In [543]:
# sklearn feature names, they are sorted in alphabetic order by default.

print(vectorizer.get_feature_names())

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']


In [544]:
# Here we will print the sklearn tfidf vectorizer idf values after applying the fit method
# After using the fit function on the corpus the vocab has 9 words in it, and each has its idf value.

print(vectorizer.idf_)

[1.91629073 1.22314355 1.51082562 1.         1.91629073 1.91629073
 1.         1.91629073 1.        ]


In [545]:
# shape of sklearn tfidf vectorizer output after applying transform method.

skl_output.shape

(4, 9)

In [546]:
# sklearn tfidf values for first line of the above corpus.
# Here the output is a sparse matrix

print(skl_output[0])

  (0, 8)	0.38408524091481483
  (0, 6)	0.38408524091481483
  (0, 3)	0.38408524091481483
  (0, 2)	0.5802858236844359
  (0, 1)	0.46979138557992045


In [547]:
# sklearn tfidf values for first line of the above corpus.
# To understand the output better, here we are converting the sparse output matrix to dense matrix and printing it.
# Notice that this output is normalized using L2 normalization. sklearn does this by default.

print(skl_output[0].toarray())

[[0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]]


### Your custom implementation

In [548]:
# Write your code here.
# Make sure its well documented and readble with appropriate comments.
# Compare your results with the above sklearn tfidf vectorizer
# You are not supposed to use any other library apart from the ones given below

from collections import Counter
from tqdm import tqdm
from scipy.sparse import csr_matrix
import math
import operator
from sklearn.preprocessing import normalize
import numpy

# using fit function, we will find all unique words in the data and we will assign a dimension-number to each unique word.

# it accepts only list of sentances
def fit(dataset):    
    unique_words = set() # at first we will initialize an empty set
    # check if its list type or not
    if isinstance(dataset, (list,)):  # it will check whether the dataset is list data type or not
        for row in dataset: # for each review in the dataset
            for word in row.split(" "): # for each word in the review. #split method converts a string into list of words
                if len(word) < 2:
                    continue
                unique_words.add(word)  # it adds only unique words without any duplicates
        unique_words = sorted(list(unique_words))
        vocab = {j:i for i,j in enumerate(unique_words)}
        return vocab
    
    else:
        print("you need to pass list of sentance")

In [549]:
vocab = fit(corpus)
print(list(vocab.keys()))
print(vocab)

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
{'and': 0, 'document': 1, 'first': 2, 'is': 3, 'one': 4, 'second': 5, 'the': 6, 'third': 7, 'this': 8}


In [550]:
from collections import Counter
from scipy.sparse import csr_matrix
test = 'abc def abc def zzz zzz pqr'
a = dict(Counter(test.split()))
for i,j in a.items():
    print(i, j)

abc 2
def 2
zzz 2
pqr 1


In [407]:
def IDF(corpus, unique_words):
    idf_dict = {}
    N = len(corpus)
    for i in unique_words:
        count = 0
        for row in corpus:
            if i in row.split(' '):
                count += 1
                idf_dict[i] = 1+(math.log((1+N)/(count+1)))
    return idf_dict
IDF(corpus,vocab)
idf_val = IDF(corpus,vocab)
print(idf_val)

{'and': 1.916290731874155, 'document': 1.2231435513142097, 'first': 1.5108256237659907, 'is': 1.0, 'one': 1.916290731874155, 'second': 1.916290731874155, 'the': 1.0, 'third': 1.916290731874155, 'this': 1.0}


In [408]:
data = []
for i in range(len(corpus)):
    data.append(corpus[i].split())
    
word_freq = {}
for i in range(len(data)):
    token = data[i]
    for w in token:
        try:
            word_freq[w].add(i)
        except:
            word_freq[w] = {i}
for i in word_freq:
    word_freq[i] = len(word_freq[i])
    
def idf():
    idfDict = {}
    for word in word_freq:
        idfDict[word] =1+ math.log((1+ len(data))/ (1 +word_freq[word]))
    return idfDict
idf()

{'this': 1.0,
 'is': 1.0,
 'the': 1.0,
 'first': 1.5108256237659907,
 'document': 1.2231435513142097,
 'second': 1.916290731874155,
 'and': 1.916290731874155,
 'third': 1.916290731874155,
 'one': 1.916290731874155}

In [360]:
def transform(dataset,vocab,idf_val):
    sparse_matrix = csr_matrix((len(dataset),len(vocab)))  #(no of rows, no of columns)
    for row in range(0,len(dataset)):
        number_of_words_in_sentence = dict(Counter(dataset[row].split()))
        for word in dataset[row].split():
            if word in list(vocab.keys()):
                tf_idf_value = (number_of_words_in_sentence[word] / len(dataset[row].split()))*(idf_val[word])
                sparse_matrix[row,vocab[word]] = tf_idf_value
    print(normalize(sparse_matrix,norm='l2',axis=1,copy=True,return_norm = False))
    output = normalize(sparse_matrix,norm='l2',axis=1,copy=True,return_norm = False)
    return output
final_output = transform(corpus,vocab,idf_val)

  (0, 1)	0.4697913855799205
  (0, 2)	0.580285823684436
  (0, 3)	0.3840852409148149
  (0, 6)	0.3840852409148149
  (0, 8)	0.3840852409148149
  (1, 1)	0.6876235979836937
  (1, 3)	0.2810886740337529
  (1, 5)	0.5386476208856762
  (1, 6)	0.2810886740337529
  (1, 8)	0.2810886740337529
  (2, 0)	0.511848512707169
  (2, 3)	0.267103787642168
  (2, 4)	0.511848512707169
  (2, 6)	0.267103787642168
  (2, 7)	0.511848512707169
  (2, 8)	0.267103787642168
  (3, 1)	0.4697913855799205
  (3, 2)	0.580285823684436
  (3, 3)	0.3840852409148149
  (3, 6)	0.3840852409148149
  (3, 8)	0.3840852409148149


In [554]:
def fit(dataset):    
    unique_words = set() # at first we will initialize an empty set
    # check if its list type or not
    if isinstance(dataset, (list,)):  # it will check whether the dataset is list data type or not
        for row in dataset: # for each review in the dataset
            for word in row.split(" "): # for each word in the review. #split method converts a string into list of words
                if len(word) < 2:
                    continue
                unique_words.add(word)  # it adds only unique words without any duplicates
        unique_words = sorted(list(unique_words))
        vocab = {j:i for i,j in enumerate(unique_words)}
        return vocab
    
    else:
        print("you need to pass list of sentance")
        
def IDF(corpus, unique_words):
    idf_dict = {}
    N = len(corpus)
    for i in unique_words:
        count = 0
        for row in corpus:
            if i in row.split(' '):
                count += 1
                idf_dict[i] = 1+(math.log((1+N)/(count+1)))
    return idf_dict
IDF(corpus,vocab)
idf_val = IDF(corpus,vocab)
print(idf_val)
'''
def transform(dataset, vocab):
    #sparse_matrix = [rows,columns,values]
    rows = []
    columns = []
    values = []
    if isinstance(dataset,(list,) ):   # if our dataset is list data type
        for idx, row in enumerate(tqdm(dataset)): # for each document in the dataset
            #print(idx)
            #print(row)
            # it will return a dict type object where key is the word and values is its frequency, {word:frequency}
            word_freq = dict(Counter(row.split()))  # A Counter is a dict subclass for counting hashable objects
            # for every unique word in the document
            for word, freq in word_freq.items():  # for each unique word in the review.  
                #print(word,end=',')
                #print(word,freq)
                if len(word) < 2:
                    continue
                if word in vocab.keys():
                    col_index = list(vocab.keys()).index(word)
                else:
                    col_index = 1
                # we will check if its there in the vocabulary that we build in fit() function
                # dict.get() function will return the values, if the key doesn't exits it will return -1
                #print(vocab)
                col_index = vocab.get(word, -1) # retreving the dimension number of a word
                #print(col_index)
                # if the word exists
                if col_index !=-1:
                    # we are storing the index of the document
                    rows.append(idx)
                    # we are storing the dimensions of the word
                    columns.append(col_index)
                    # we are storing the frequency of the word
                    tf = freq / len(row.split()) # term_frequency 
                    #𝑇𝐹(𝑡)=Number of times term t appears in a document / Total number of terms in the document/row.
                    idf_ =  vocab[word]
                    #𝐼𝐷𝐹(𝑡)=1+log𝑒[1 + Total number of documents in collection / 1+Number of documents with term t in it].
                    values.append((tf) * (idf_))
                    # normalize the sparse matrix'''
def transform(corpus,a):
    rows = []
    columns = []
    values = []
    unique_words = set()
    if isinstance(corpus,(list,)):
        for row in corpus:
            for word in row.split(' '):
                if len(word) < 2:
                    continue
                unique_words.add(word)
        unique_words = sorted(list(unique_words))
        vocab = {j:i for i,j in enumerate(unique_words)}
    else:
        print("you need to pass list of strings")
    
    if isinstance(corpus, (list,)):
        for idx,row in enumerate(tqdm(corpus)):
            word_freq = dict(Counter(row.split()))
            for word,freq in word_freq.items():
                if len(word) < 1:
                    continue
                col_index = vocab.get(word,-1)
                if col_index!=-1:
                    
                    
                    wdc = freq
                    twc = len(row.split())
                    tf = (wdc/twc)
                    tf_idf = tf*a[word]
                    values.append(tf_idf)
                    columns.append(col_index)
                    rows.append(idx)
        return csr_matrix((values , (rows,columns)), shape = (len(corpus),len(vocab)) )
    else:
        print("you need to pass list of strings")
        
y = normalize(transform(corpus,a),norm='l2',axis=1,copy=True,return_norm=False)
print(y)


{'and': 1.916290731874155, 'document': 1.2231435513142097, 'first': 1.5108256237659907, 'is': 1.0, 'one': 1.916290731874155, 'second': 1.916290731874155, 'the': 1.0, 'third': 1.916290731874155, 'this': 1.0}



  0%|          | 0/4 [00:00<?, ?it/s]


KeyError: 'this'

In [411]:
def transform(dataset, vocab):
    #sparse_matrix = [rows,columns,values]
    rows = []
    columns = []
    values = []
    if isinstance(dataset,(list,) ):   # if our dataset is list data type
        for idx, row in enumerate(tqdm(dataset)): # for each document in the dataset
            #print(idx)
            #print(row)
            # it will return a dict type object where key is the word and values is its frequency, {word:frequency}
            word_freq = dict(Counter(row.split()))  # A Counter is a dict subclass for counting hashable objects
            # for every unique word in the document
            for word, freq in word_freq.items():  # for each unique word in the review.  
                #print(word,end=',')
                #print(word,freq)
                if len(word) < 2:
                    continue
                if word in vocab.keys():
                    col_index = list(vocab.keys()).index(word)
                else:
                    col_index = 1
                # we will check if its there in the vocabulary that we build in fit() function
                # dict.get() function will return the values, if the key doesn't exits it will return -1
                #print(vocab)
                col_index = vocab.get(word, -1) # retreving the dimension number of a word
                #print(col_index)
                # if the word exists
                if col_index !=-1:
                    # we are storing the index of the document
                    rows.append(idx)
                    # we are storing the dimensions of the word
                    columns.append(col_index)
                    # we are storing the frequency of the word
                    tf = freq / len(row.split()) # term_frequency 
                    #𝑇𝐹(𝑡)=Number of times term t appears in a document / Total number of terms in the document/row.
                    idf_ =  1+math.log((1+len(dataset))/float(1+len(word)))
                    #𝐼𝐷𝐹(𝑡)=1+log𝑒[1 + Total number of documents in collection / 1+Number of documents with term t in it].
                    values.append((tf) * (idf_))
                    # normalize the sparse matrix
        g = normalize(csr_matrix((values, (rows,columns)), shape=(len(dataset),len(vocab))),norm='l2',axis=1,copy = True,return_norm= False)
        print(vocab)
        return g
    else:
        print("you need to pass list of strings")
print(transform(corpus,vocab)[0])



100%|██████████| 4/4 [00:00<?, ?it/s]


{'and': 0, 'document': 1, 'first': 2, 'is': 3, 'one': 4, 'second': 5, 'the': 6, 'third': 7, 'this': 8}
  (0, 1)	0.17392515520138968
  (0, 2)	0.34500303127183624
  (0, 3)	0.6374625921146895
  (0, 6)	0.5160809073422826
  (0, 8)	0.4219299580885484


In [362]:
vocab = fit(corpus)
print(list(vocab.keys()))
print(transform(corpus, vocab,idf_val).toarray()) 

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']


C:\Users\basin\Anaconda3\lib\site-packages\scipy\sparse\_index.py:84: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_intXint(row, col, x.flat[0])


  (0, 1)	0.4697913855799205
  (0, 2)	0.580285823684436
  (0, 3)	0.3840852409148149
  (0, 6)	0.3840852409148149
  (0, 8)	0.3840852409148149
  (1, 1)	0.6876235979836937
  (1, 3)	0.2810886740337529
  (1, 5)	0.5386476208856762
  (1, 6)	0.2810886740337529
  (1, 8)	0.2810886740337529
  (2, 0)	0.511848512707169
  (2, 3)	0.267103787642168
  (2, 4)	0.511848512707169
  (2, 6)	0.267103787642168
  (2, 7)	0.511848512707169
  (2, 8)	0.267103787642168
  (3, 1)	0.4697913855799205
  (3, 2)	0.580285823684436
  (3, 3)	0.3840852409148149
  (3, 6)	0.3840852409148149
  (3, 8)	0.3840852409148149
[[0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]
 [0.         0.6876236  0.         0.28108867 0.         0.53864762
  0.28108867 0.         0.28108867]
 [0.51184851 0.         0.         0.26710379 0.51184851 0.
  0.26710379 0.51184851 0.26710379]
 [0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]]


## Comparing results with countvectorizer¶

In [363]:
from sklearn.feature_extraction.text import CountVectorizer

vec = CountVectorizer(analyzer='word')

vec.fit(corpus)
feature_matrix_2 = vec.transform(corpus)
print(feature_matrix_2.toarray())

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


## Task-2

<font face='georgia'>
    <h4><strong>2. Implement max features functionality:</strong></h4>

<ul>
    <li> As a part of this task you have to modify your fit and transform functions so that your vocab will contain only 50 terms with top idf scores.</li>
    <br>
    <li>This task is similar to your previous task, just that here your vocabulary is limited to only top 50 features names based on their idf values. Basically your output will have exactly 50 columns and the number of rows will depend on the number of documents you have in your corpus.</li>
    <br>
    <li>Here you will be give a pickle file, with file name <strong>cleaned_strings</strong>. You would have to load the corpus from this file and use it as input to your tfidf vectorizer.</li>
    <br>
    <li>Steps to approach this task:
    <ol>
        <li> You would have to write both fit and transform methods for your custom implementation of tfidf vectorizer, just like in the previous task. Additionally, here you have to limit the number of features generated to 50 as described above.</li>
        <li> Now sort your vocab based in descending order of idf values and print out the words in the sorted voacb after you fit your data. Here you should be getting only 50 terms in your vocab. And make sure to print idf values for each term in your vocab. </li>
        <li> Make sure the output of your implementation is a sparse matrix. Before generating the final output, you need to normalize your sparse matrix using L2 normalization. You can refer to this link https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.normalize.html </li>
        <li> Now check the output of a single document in your collection of documents,  you can convert the sparse matrix related only to that document into dense matrix and print it. And this dense matrix should contain 1 row and 50 columns. </li>
        </ol>
    </li>
    <br>
   </ul>

In [499]:
# Below is the code to load the cleaned_strings pickle file provided
# Here corpus is of list type

import pickle
with open('cleaned_strings', 'rb') as f:
    corpus = pickle.load(f)
    
# printing the length of the corpus loaded
print("Number of documents in corpus = ",len(corpus))

Number of documents in corpus =  746


In [500]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
vectorizer.fit(corpus)
skl_output = vectorizer.transform(corpus)

In [501]:
# sklearn feature names, they are sorted in alphabetic order by default.

print(vectorizer.get_feature_names())

['aailiyah', 'abandoned', 'ability', 'abroad', 'absolutely', 'abstruse', 'abysmal', 'academy', 'accents', 'accessible', 'acclaimed', 'accolades', 'accurate', 'accurately', 'accused', 'achievement', 'achille', 'ackerman', 'act', 'acted', 'acting', 'action', 'actions', 'actor', 'actors', 'actress', 'actresses', 'actually', 'adams', 'adaptation', 'add', 'added', 'addition', 'admins', 'admiration', 'admitted', 'adorable', 'adrift', 'adventure', 'advise', 'aerial', 'aesthetically', 'affected', 'affleck', 'afraid', 'africa', 'afternoon', 'age', 'aged', 'ages', 'ago', 'agree', 'agreed', 'aimless', 'air', 'aired', 'akasha', 'akin', 'alert', 'alexander', 'alike', 'allison', 'allow', 'allowing', 'almost', 'along', 'alongside', 'already', 'also', 'although', 'always', 'amateurish', 'amaze', 'amazed', 'amazing', 'amazingly', 'america', 'american', 'americans', 'among', 'amount', 'amusing', 'amust', 'anatomist', 'angel', 'angela', 'angeles', 'angelina', 'angle', 'angles', 'angry', 'anguish', 'angus

In [502]:
print(vectorizer.idf_)

[6.922918   6.922918   6.22977082 ... 6.922918   6.5174529  6.922918  ]


In [503]:
# shape of sklearn tfidf vectorizer output after applying transform method.

skl_output.shape

(746, 2886)

In [504]:
features = vectorizer.get_feature_names()
len(features)

2886

In [505]:
print(skl_output[0])

  (0, 2878)	0.35781145622317734
  (0, 2287)	0.3377679916467555
  (0, 1653)	0.35781145622317734
  (0, 1651)	0.16192317905848022
  (0, 1545)	0.30566026894803877
  (0, 720)	0.4123943870778812
  (0, 688)	0.4123943870778812
  (0, 53)	0.4123943870778812


In [506]:
# sklearn tfidf values for first line of the above corpus.
# To understand the output better, here we are converting the sparse output matrix to dense matrix and printing it.
# Notice that this output is normalized using L2 normalization. sklearn does this by default.

print(skl_output[0].toarray())

[[0. 0. 0. ... 0. 0. 0.]]


In [507]:
# Write your code here.
# Try not to hardcode any values.
# Make sure its well documented and readble with appropriate comments.



from collections import Counter
from tqdm import tqdm
from scipy.sparse import csr_matrix
import math
import operator
from sklearn.preprocessing import normalize
import numpy

# using fit function, we will find all unique words in the data and we will assign a dimension-number to each unique word.

def sorteddic(tup,d):
    d = dict(tup)
    return d

# it accepts only list of sentances
def fit(dataset):    
    unique_words = set() # at first we will initialize an empty set
    d1 = {}
    # check if its list type or not
    if isinstance(dataset, (list,)):  # it will check whether the dataset is list data type or not
        for row in dataset: # for each review in the dataset
            for word in row.split(" "): # for each word in the review. #split method converts a string into list of words
                if len(word) < 2:
                    continue
                unique_words.add(word)  # it adds only unique words without any duplicates
        unique_words = sorted(list(unique_words))
        vocab = {j:i for i,j in enumerate(unique_words)}
        a = dict(zip(unique_words,vocab))
        m = Counter(a)
        g = m.most_common(50)
        return sorteddic(g,d1)
        
    else:
        print("you need to pass list of sentance")


In [508]:
a = fit(corpus)
#print(list(a.keys()))
print(a)

{'zombiez': 'zombiez', 'zombie': 'zombie', 'zillion': 'zillion', 'yun': 'yun', 'youtube': 'youtube', 'youthful': 'youthful', 'younger': 'younger', 'young': 'young', 'yet': 'yet', 'yes': 'yes', 'yelps': 'yelps', 'years': 'years', 'year': 'year', 'yeah': 'yeah', 'yawn': 'yawn', 'yardley': 'yardley', 'wrote': 'wrote', 'wrong': 'wrong', 'written': 'written', 'writing': 'writing', 'writers': 'writers', 'writer': 'writer', 'write': 'write', 'wrap': 'wrap', 'wow': 'wow', 'woven': 'woven', 'wouldnt': 'wouldnt', 'would': 'would', 'worthy': 'worthy', 'worthwhile': 'worthwhile', 'worthless': 'worthless', 'worth': 'worth', 'worst': 'worst', 'worse': 'worse', 'worry': 'worry', 'world': 'world', 'works': 'works', 'working': 'working', 'worked': 'worked', 'work': 'work', 'words': 'words', 'word': 'word', 'wooden': 'wooden', 'woo': 'woo', 'wont': 'wont', 'wong': 'wong', 'wonderfully': 'wonderfully', 'wonderful': 'wonderful', 'wondered': 'wondered', 'wonder': 'wonder'}


In [316]:
data = []
for i in range(len(corpus)):
    data.append(corpus[i].split())
    
word_freq = {}
for i in range(len(data)):
    token = data[i]
    for w in token:
        try:
            word_freq[w].add(i)
        except:
            word_freq[w] = {i}
for i in word_freq:
    word_freq[i] = len(word_freq[i])
    
def idf():
    idfDict = {}
    for word in word_freq:
        idfDict[word] =1+ math.log((1+ len(data))/ (1 +word_freq[word]))
    return idfDict
idf()

{'this': 1.0,
 'is': 1.0,
 'the': 1.0,
 'first': 1.5108256237659907,
 'document': 1.2231435513142097,
 'second': 1.916290731874155,
 'and': 1.916290731874155,
 'third': 1.916290731874155,
 'one': 1.916290731874155}

In [509]:
def IDF(corpus, unique_words):
    idf_dict = {}
    N = len(corpus)
    for i in unique_words:
        count = 0
        for row in corpus:
            if i in row.split(' '):
                count += 1
                idf_dict[i] = 1+(math.log((1+N)/(count+1)))
    return idf_dict
IDF(corpus,a)
idf_val = IDF(corpus,a)
print(idf_val)

{'zombiez': 6.922918004572872, 'zombie': 6.517452896464707, 'zillion': 6.922918004572872, 'yun': 6.922918004572872, 'youtube': 6.922918004572872, 'youthful': 6.922918004572872, 'younger': 6.922918004572872, 'young': 6.006627272698717, 'yet': 5.824305715904762, 'yes': 6.229770824012927, 'yelps': 6.922918004572872, 'years': 5.05111582767128, 'year': 6.229770824012927, 'yeah': 6.517452896464707, 'yawn': 6.922918004572872, 'yardley': 6.922918004572872, 'wrote': 6.922918004572872, 'wrong': 6.229770824012927, 'written': 5.536623643452981, 'writing': 4.9770078555175585, 'writers': 6.922918004572872, 'writer': 6.229770824012927, 'write': 6.517452896464707, 'wrap': 6.922918004572872, 'wow': 6.922918004572872, 'woven': 6.922918004572872, 'wouldnt': 6.922918004572872, 'would': 4.283860674957613, 'worthy': 6.922918004572872, 'worthwhile': 6.922918004572872, 'worthless': 6.922918004572872, 'worth': 4.9770078555175585, 'worst': 5.218169912334447, 'worse': 5.218169912334447, 'worry': 6.92291800457287

In [486]:
k=Counter(idf_val)
top_idf = dict(k.most_common(50))
print(top_idf)

{'aailiyah': 6.922918004572872, 'abandoned': 6.922918004572872, 'abroad': 6.922918004572872, 'abstruse': 6.922918004572872, 'academy': 6.922918004572872, 'accents': 6.922918004572872, 'accessible': 6.922918004572872, 'acclaimed': 6.922918004572872, 'accolades': 6.922918004572872, 'accurate': 6.922918004572872, 'accurately': 6.922918004572872, 'achille': 6.922918004572872, 'ackerman': 6.922918004572872, 'actions': 6.922918004572872, 'adams': 6.922918004572872, 'add': 6.922918004572872, 'added': 6.922918004572872, 'admins': 6.922918004572872, 'admiration': 6.922918004572872, 'admitted': 6.922918004572872, 'adrift': 6.922918004572872, 'adventure': 6.922918004572872, 'aesthetically': 6.922918004572872, 'affected': 6.922918004572872, 'affleck': 6.922918004572872, 'afternoon': 6.922918004572872, 'aged': 6.922918004572872, 'ages': 6.922918004572872, 'agree': 6.922918004572872, 'agreed': 6.922918004572872, 'aimless': 6.922918004572872, 'aired': 6.922918004572872, 'akasha': 6.922918004572872, '

In [476]:
feature_array = np.array(tfidf.get_feature_names())
tfidf_sorting = np.argsort(response.toarray()).flatten()[::-1]

n = 3
top_n = feature_array[tfidf_sorting][:n]

NameError: name 'tfidf' is not defined

In [533]:
def transform(dataset, a):
    #sparse_matrix = [rows,columns,values]
    rows = []
    columns = []
    values = []
    unique_words = set()
    
    vocab = {j:i for i,j in enumerate(a)}
    
    if isinstance(dataset,(list,) ):   # if our dataset is list data type
        for idx, row in enumerate(tqdm(dataset)): # for each document in the dataset
            #print(idx)
            #print(row)
            # it will return a dict type object where key is the word and values is its frequency, {word:frequency}
            word_freq = dict(Counter(row.split()))  # A Counter is a dict subclass for counting hashable objects
            # for every unique word in the document
            for word, freq in word_freq.items():  # for each unique word in the review.  
                #print(word,end=',')
                #print(word,freq)
                if len(word) < 2:
                    continue
                # we will check if its there in the vocabulary that we build in fit() function
                # dict.get() function will return the values, if the key doesn't exits it will return -1
                #print(vocab)
                col_index = vocab.get(word, -1) # retreving the dimension number of a word
                #print(col_index)
                # if the word exists
                if col_index !=-1:
                    wdc = freq
                    twc = sum([1 for w in row.split()])
                    # we are storing the index of the document
                    rows.append(idx)
                    # we are storing the dimensions of the word
                    columns.append(col_index)
                    #tf = (wdc/twc)
                    #tf_idf = tf*int(a[word])
                    #values.append(tf_idf)
                    # we are storing the frequency of the word
                    tf = freq / float(len(row)) # term_frequency 
                    #tf_idf = tf*int(a[word])
                    values.append(tf_idf)
                    #𝑇𝐹(𝑡)=Number of times term t appears in a document / Total number of terms in the document/row.
                    idf_ =  1 + math.log((1+len(dataset))/float(1+len(word)))
                    #𝐼𝐷𝐹(𝑡)=1+log𝑒[1 + Total number of documents in collection / 1+Number of documents with term t in it].
                    values.append((tf) * (idf_))
        return csr_matrix((values, (rows,columns)), shape=(len(dataset),len(vocab)))
    else:
        print("you need to pass list of strings")
        

In [520]:
def transform(dataset,vocab,idf_val):
    sparse_matrix = csr_matrix((len(dataset),len(vocab)))  #(no of rows, no of columns)
    for row in range(0,len(dataset)):
        number_of_words_in_sentence = dict(Counter(dataset[row].split()))
        for word in dataset[row].split():
            if word in list(vocab.keys()):
                tf_idf_value = (number_of_words_in_sentence[word] / len(dataset[row].split()))*(idf_val[word])
                sparse_matrix[row,vocab[word]] = tf_idf_value
    print(normalize(sparse_matrix,norm='l2',axis=1,copy=True,return_norm = False))
    output = normalize(sparse_matrix,norm='l2',axis=1,copy=True,return_norm = False)
    return output
final_output = transform(corpus,a,idf_val)

IndexError: Index dimension must be <= 2

In [482]:

tfidf_sorting = np.argsort(transform(corpus,vocab,idf_val).toarray()).flatten()[::-1]

n = 3
top_n = [tfidf_sorting][:n]

  (0, 53)	0.4123943870778812
  (0, 688)	0.4123943870778812
  (0, 720)	0.4123943870778812
  (0, 1545)	0.30566026894803877
  (0, 1651)	0.16192317905848022
  (0, 1653)	0.35781145622317734
  (0, 2287)	0.3377679916467555
  (0, 2878)	0.35781145622317734
  (1, 149)	0.33656662310141316
  (1, 374)	0.23983327446209923
  (1, 966)	0.3766212179754885
  (1, 1132)	0.3276587847617171
  (1, 1511)	0.3471023596650289
  (1, 1676)	0.40005165395840037
  (1, 1712)	0.16744040526541595
  (1, 2446)	0.35999705908432506
  (1, 2764)	0.3766212179754885
  (2, 20)	0.16253663363642504
  (2, 64)	0.21707671739759155
  (2, 89)	0.26626377741607504
  (2, 124)	0.28282863381171675
  (2, 145)	0.28282863381171675
  (2, 201)	0.26626377741607504
  (2, 236)	0.21707671739759155
  (2, 320)	0.21318291886861856
  :	:
  (741, 268)	0.3741383656784868
  (741, 429)	0.43121191150476473
  (741, 1096)	0.33752654806602456
  (741, 1354)	0.43121191150476473
  (741, 1422)	0.40595646514525013
  (741, 2471)	0.35318031934226296
  (741, 2785)	0.290

In [383]:
print(transform(corpus,vocab,idf_val)[0])

C:\Users\basin\Anaconda3\lib\site-packages\scipy\sparse\_index.py:84: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_intXint(row, col, x.flat[0])


  (0, 53)	0.4123943870778812
  (0, 688)	0.4123943870778812
  (0, 720)	0.4123943870778812
  (0, 1545)	0.30566026894803877
  (0, 1651)	0.16192317905848022
  (0, 1653)	0.35781145622317734
  (0, 2287)	0.3377679916467555
  (0, 2878)	0.35781145622317734
  (1, 149)	0.33656662310141316
  (1, 374)	0.23983327446209923
  (1, 966)	0.3766212179754885
  (1, 1132)	0.3276587847617171
  (1, 1511)	0.3471023596650289
  (1, 1676)	0.40005165395840037
  (1, 1712)	0.16744040526541595
  (1, 2446)	0.35999705908432506
  (1, 2764)	0.3766212179754885
  (2, 20)	0.16253663363642504
  (2, 64)	0.21707671739759155
  (2, 89)	0.26626377741607504
  (2, 124)	0.28282863381171675
  (2, 145)	0.28282863381171675
  (2, 201)	0.26626377741607504
  (2, 236)	0.21707671739759155
  (2, 320)	0.21318291886861856
  :	:
  (741, 268)	0.3741383656784868
  (741, 429)	0.43121191150476473
  (741, 1096)	0.33752654806602456
  (741, 1354)	0.43121191150476473
  (741, 1422)	0.40595646514525013
  (741, 2471)	0.35318031934226296
  (741, 2785)	0.290

In [385]:
vocab = fit(corpus)
print(list(vocab.keys()))

print('='*100)
print(transform(corpus, vocab,idf_val).toarray()) 

['aailiyah', 'abandoned', 'ability', 'abroad', 'absolutely', 'abstruse', 'abysmal', 'academy', 'accents', 'accessible', 'acclaimed', 'accolades', 'accurate', 'accurately', 'accused', 'achievement', 'achille', 'ackerman', 'act', 'acted', 'acting', 'action', 'actions', 'actor', 'actors', 'actress', 'actresses', 'actually', 'adams', 'adaptation', 'add', 'added', 'addition', 'admins', 'admiration', 'admitted', 'adorable', 'adrift', 'adventure', 'advise', 'aerial', 'aesthetically', 'affected', 'affleck', 'afraid', 'africa', 'afternoon', 'age', 'aged', 'ages', 'ago', 'agree', 'agreed', 'aimless', 'air', 'aired', 'akasha', 'akin', 'alert', 'alexander', 'alike', 'allison', 'allow', 'allowing', 'almost', 'along', 'alongside', 'already', 'also', 'although', 'always', 'amateurish', 'amaze', 'amazed', 'amazing', 'amazingly', 'america', 'american', 'americans', 'among', 'amount', 'amusing', 'amust', 'anatomist', 'angel', 'angela', 'angeles', 'angelina', 'angle', 'angles', 'angry', 'anguish', 'angus

C:\Users\basin\Anaconda3\lib\site-packages\scipy\sparse\_index.py:84: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_intXint(row, col, x.flat[0])


  (0, 53)	0.4123943870778812
  (0, 688)	0.4123943870778812
  (0, 720)	0.4123943870778812
  (0, 1545)	0.30566026894803877
  (0, 1651)	0.16192317905848022
  (0, 1653)	0.35781145622317734
  (0, 2287)	0.3377679916467555
  (0, 2878)	0.35781145622317734
  (1, 149)	0.33656662310141316
  (1, 374)	0.23983327446209923
  (1, 966)	0.3766212179754885
  (1, 1132)	0.3276587847617171
  (1, 1511)	0.3471023596650289
  (1, 1676)	0.40005165395840037
  (1, 1712)	0.16744040526541595
  (1, 2446)	0.35999705908432506
  (1, 2764)	0.3766212179754885
  (2, 20)	0.16253663363642504
  (2, 64)	0.21707671739759155
  (2, 89)	0.26626377741607504
  (2, 124)	0.28282863381171675
  (2, 145)	0.28282863381171675
  (2, 201)	0.26626377741607504
  (2, 236)	0.21707671739759155
  (2, 320)	0.21318291886861856
  :	:
  (741, 268)	0.3741383656784868
  (741, 429)	0.43121191150476473
  (741, 1096)	0.33752654806602456
  (741, 1354)	0.43121191150476473
  (741, 1422)	0.40595646514525013
  (741, 2471)	0.35318031934226296
  (741, 2785)	0.290

In [386]:
from sklearn.feature_extraction.text import CountVectorizer

vec = CountVectorizer(analyzer='word')

vec.fit(corpus)
feature_matrix_2 = vec.transform(corpus)
print(feature_matrix_2.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [392]:
import pandas as pd
def top_tfidf_features(row, features, top_n=50):
    # get top n tfidf values in row and return them with their corresponding ranks
    topn_ids = np.argsort(row)[::-1][:top_n]#sorting the top 25 in descending order of review given in calling function, till 25
    #np.argsort(row)[::-1] # sorting the row according to given in calling function[which review/row from descending order]
    #np.argsort(row)[::-1][:top_n] == it sort the row till 25 values
    top_feats = [(features[i],row[i]) for i in topn_ids]  # topfeatures = features,tfidf values and iterates till 25
    df = pd.DataFrame(top_feats)              # creating a dataframe of top_feats
    df.columns = ['feature','idf']          # creating the columns
    return df

top_tfidf = top_tfidf_features(feature_matrix_2[0,:].toarray()[0],features,50)

# row = i had get the review 1 and converted into sparse matrix 

In [393]:
top_tfidf

feature  idf
0      drifting    1
1         movie    1
2       aimless    1
3         young    1
4        moving    1
5          slow    1
6    distressed    1
7           man    1
8       zombiez    0
9       fishnet    0
10       flakes    0
11         flag    0
12         five    0
13          fit    0
14       fisted    0
15        first    0
16         fish    0
17   flashbacks    0
18         fire    0
19     finished    0
20  fingernails    0
21       finest    0
22         fine    0
23        finds    0
24         find    0
25      flaming    0
26         flaw    0
27         flat    0
28      finally    0
29       forced    0
30        force    0
31     football    0
32      footage    0
33      foolish    0
34      follows    0
35    following    0
36       follow    0
37       fodder    0
38        focus    0
39        flynn    0
40       flying    0
41       flowed    0
42      florida    0
43       flicks    0
44        flick    0
45      fleshed    0
46        flaws    0
47       flawed    0
48    financial    0
49        films    0