## BAG OF WORDS

In [3]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
from tqdm import tqdm
import os

In [86]:
# tqdm : will give you a (very fast) progress bar. You also use tqdm more explicitly,

from tqdm import tqdm # tqdm is a library that helps us to visualize the runtime of for loop. refer this to know more about tqdm
#https://tqdm.github.io/


#fit: With this function, we will find all unique words in the data and we will assign a dimension-number to each unique word.

#We will create a python dictionary to save all the unique words, such that the key of dictionary represents a unique word 
#                                       and the corresponding value represent it's dimension-number.

#For example, if you have a review, __'very bad pizza'__ then you can represent each unique word with a dimension_number as,
#dict = { 'very' : 1, 'bad' : 2, 'pizza' : 3}


# it accepts only list of sentances
def fit(dataset):    
    
    unique_words = set() # at first we will initialize an empty set
    # check if its list type or not
    if isinstance(dataset, (list,)):   # it checks whether the dataset is of list data type or not
        for row in dataset: # for each review/row in the dataset
            #print(row)   # abc def aaa prq mn pqr aaaaaaa aaa abbb baaa
            for word in row.split(" "): # for each word in the review. #split method converts a string into list of words
                #print(word)  # abc          here it splits the entire word and segregate into the words in line by line
                #             # def...
                if len(word) < 2:       # if length of each word is less than 2 it just skips the statement
                    continue
                unique_words.add(word)    # it adds all the unique words into the set
                '''print(unique_words)     # {'abc'}
                                           # {'def', 'abc'}
                                           # {'def', 'abc', 'aaa'}......'''
        unique_words = sorted(list(unique_words))# here all the unique values converts into the list in sorted order
        #print(unique_words)  #['aaa', 'aaaaaaa', 'abbb', 'abc', 'baaa', 'def', 'mn', 'pqr', 'prq']
        vocab = {j:i for i,j in enumerate(unique_words)}#finally all the unique words with dimension number store into dict
        #print(vocab) #{'aaa': 0, 'aaaaaaa': 1, 'abbb': 2, 'abc': 3, 'baaa': 4, 'def': 5, 'mn': 6, 'pqr': 7, 'prq': 8}
        return vocab
    else:
        print("you need to pass list of sentance")

In [87]:
vocab = fit(["abc def aaa prq mn pqr aaaaaaa aaa abbb baaa"])  # here i stored entire in elements in the single list
print(vocab)          # here set wont accept duplicate values. thus we have only 9 unique words from 10

{'aaa': 0, 'aaaaaaa': 1, 'abbb': 2, 'abc': 3, 'baaa': 4, 'def': 5, 'mn': 6, 'pqr': 7, 'prq': 8}


In [88]:
vocab = fit(["abc def aaa prq", "lmn pqr aaaaaaa aaa abbb baaa"]) # here we have two reviews
print(vocab)

{'aaa': 0, 'aaaaaaa': 1, 'abbb': 2, 'abc': 3, 'baaa': 4, 'def': 5, 'lmn': 6, 'pqr': 7, 'prq': 8}


In [37]:
 # from above matrix we only have 3 non zero values so better to store it as sparse matrix rather dense matrix
# in spasre matrix we are only storing non zero values
from sys import getsizeof
import numpy as np
# we store every element here
a = np.array([[1, 0, 0, 0, 0], [0, 0, 0, 1, 0], [0, 0, 4, 0, 0]])   # dense matrix
print(getsizeof(a))

# here we are storing only non zero elements here (row, col, value)
a = [ (0, 0, 1), (1, 3, 1), (2,2,4)]                                # sparse matrix
# with this way of storing we are saving alomost 50% memory for this example
print(getsizeof(a))

172
88


 How to write a sparse matrix

You can use csr_matrix() method of scipy.sparse to write a sparse matrix.

You need to pass indices of non-zero elements into csr_matrix() for creating a sparse matrix.
You also need to pass element value of each pair of indices.
eg: [ (0, 0, 1), (1, 3, 1), (2,2,4)]   [row,column,value]

You can use lists to save the indices of non-zero elements and their corresponding element values.

 eg: assume you have a matrix
   [[1, 0, 0], 
    [0, 0, 1], 
    [4, 0, 6]] 
list_of_indices = [(0,0), (1,2), (2,0), (2,2)]
And you can save the corresponding element values as,
element_values = [1, 1, 4, 6]


In [74]:
# Transform Method
# With this function, we will write a feature matrix using sprase matrix.

# how Counter works : dict subclass for counting hashable objects
from collections import Counter
from scipy.sparse import csr_matrix

#How to write a sparse matrix
#You can use csr_matrix() method of scipy.sparse to write a sparse matrix.

test = 'abc def abc def zzz zzz pqr'
#print(test.split())  #['abc', 'def', 'abc', 'def', 'zzz', 'zzz', 'pqr']
word_frequency = dict(Counter(test.split()))
#print(Counter(test.split()))  # Counter({'abc': 2, 'def': 2, 'zzz': 2, 'pqr': 1}) it returns occurance of words in dictionary
#print(a) # {'abc': 2, 'def': 2, 'zzz': 2, 'pqr': 1}
#print(a.items())   #dict_items([('abc', 2), ('def', 2), ('zzz', 2), ('pqr', 1)])
for i,j in word_frequency.items():
    print(i,j)

abc 2
def 2
zzz 2
pqr 1


In [107]:
# note that we are need to send the preprocessing text here, we have not inlcuded the processing

def transform(dataset, vocab):  # [corpus(collection of reviews) , {key:value}]
    # sparse matrix : # here we are storing only non zero elements here (row, col,elmenet_values)
    rows = []
    columns = []
    values = []
    if isinstance(dataset, (list,)):  # checks whether the dataset is of list type or not
        for idx,row in enumerate(tqdm(dataset)):  # for each index[dimension_number],row/review in dataset
            # it will return a dict type object where key is the word and values is its frequency, {word:frequency},{row,index}
            #print(idx) #0
                        #1
            #print(row) #the method of lagrange multipliers is the economists workhorse for solving optimization problems
                        #the technique is a centerpiece of economic theory but unfortunately its usually taught poorly
            word_freq = dict(Counter(row.split()))
            #print(row.split())#['the', 'method', 'of', 'lagrange', 'multipliers', 'is', 'the', 'economists', 'workhorse', 'for', 'solving', 'optimization', 'problems']
                             #['the', 'technique', 'is', 'a', 'centerpiece', 'of', 'economic', 'theory', 'but', 'unfortunately', 'its', 'usually', 'taught', 'poorly']

            #print(word_freq) #{'the': 2, 'method': 1, 'of': 1, 'lagrange': 1, 'multipliers': 1, 'is': 1, 'economists': 1, 'workhorse': 1, 'for': 1, 'solving': 1, 'optimization': 1, 'problems': 1}
                             #{'the': 1, 'technique': 1, 'is': 1, 'a': 1, 'centerpiece': 1, 'of': 1, 'economic': 1, 'theory': 1, 'but': 1, 'unfortunately': 1, 'its': 1, 'usually': 1, 'taught': 1, 'poorly': 1}
            
            #print(word_freq.items()) #dict_items([('the', 2), ('method', 1), ('of', 1), ('lagrange', 1), ('multipliers', 1), ('is', 1), ('economists', 1), ('workhorse', 1), ('for', 1), ('solving', 1), ('optimization', 1), ('problems', 1)])
                                     #dict_items([('the', 1), ('technique', 1), ('is', 1), ('a', 1), ('centerpiece', 1), ('of', 1), ('economic', 1), ('theory', 1), ('but', 1), ('unfortunately', 1), ('its', 1), ('usually', 1), ('taught', 1), ('poorly', 1)])            
            for word, freq in word_freq.items():  # for each unique word in the review.
                #print(word)  #the             # each unique words
                             #method
                             #of
                             #lagrange
                             #multipliers
                             #is
                             #economists
                #print(freq)  #2
                             #1
                             #1 ........
                if len(word) < 2:
                    continue
                # we will check if its there in the vocabulary that we build in fit() function
                # dict.get() function will return the values, if the key doesn't exits it will return -1
                
                col_index = vocab.get(word, -1) # retreving the dimension number of a word
                                                # vocab which we give while calling the function
                #print(col_index) #17 8 10 7 9 5 3 21 4 14 11 13  line by line not in order
                                 #17 16 5 1 10 2 18 0 19 6 20 15 12
                # if the word exists
                if col_index != -1:
                    # we are storing the index of the document
                    rows.append(idx)
                    # we are storing the dimensions of the word
                    columns.append(col_index)
                    # we are storing the frequency of the word
                    values.append(freq)  # word occurance 2 1 1 1 1 1 1 1 1
        #return sparse matrix
        return csr_matrix((values , (rows,columns)), shape = (len(dataset),len(vocab)) )
    else:
        print("you need to pass list of strings")
                    


strings = ["the method of lagrange multipliers is the economists workhorse for solving optimization problems",
           "the technique is a centerpiece of economic theory but unfortunately its usually taught poorly"]
vocab = fit(strings)
print('VOCAB :',vocab)
print('='*100)
print('VOCAB kEYS:',list(vocab.keys()))
print('='*100)
print('sparse matrix',list(vocab.keys()),transform(strings, vocab).toarray())
print('='*100)
print(transform(strings,vocab))


VOCAB : {'but': 0, 'centerpiece': 1, 'economic': 2, 'economists': 3, 'for': 4, 'is': 5, 'its': 6, 'lagrange': 7, 'method': 8, 'multipliers': 9, 'of': 10, 'optimization': 11, 'poorly': 12, 'problems': 13, 'solving': 14, 'taught': 15, 'technique': 16, 'the': 17, 'theory': 18, 'unfortunately': 19, 'usually': 20, 'workhorse': 21}
VOCAB kEYS: ['but', 'centerpiece', 'economic', 'economists', 'for', 'is', 'its', 'lagrange', 'method', 'multipliers', 'of', 'optimization', 'poorly', 'problems', 'solving', 'taught', 'technique', 'the', 'theory', 'unfortunately', 'usually', 'workhorse']



100%|██████████| 2/2 [00:00<?, ?it/s]


sparse matrix ['but', 'centerpiece', 'economic', 'economists', 'for', 'is', 'its', 'lagrange', 'method', 'multipliers', 'of', 'optimization', 'poorly', 'problems', 'solving', 'taught', 'technique', 'the', 'theory', 'unfortunately', 'usually', 'workhorse'] [[0 0 0 1 1 1 0 1 1 1 1 1 0 1 1 0 0 2 0 0 0 1]
 [1 1 1 0 0 1 1 0 0 0 1 0 1 0 0 1 1 1 1 1 1 0]]



100%|██████████| 2/2 [00:00<00:00, 2011.66it/s]


  (0, 3)	1
  (0, 4)	1
  (0, 5)	1
  (0, 7)	1
  (0, 8)	1
  (0, 9)	1
  (0, 10)	1
  (0, 11)	1
  (0, 13)	1
  (0, 14)	1
  (0, 17)	2
  (0, 21)	1
  (1, 0)	1
  (1, 1)	1
  (1, 2)	1
  (1, 5)	1
  (1, 6)	1
  (1, 10)	1
  (1, 12)	1
  (1, 15)	1
  (1, 16)	1
  (1, 17)	1
  (1, 18)	1
  (1, 19)	1
  (1, 20)	1


In [ ]:
strings = ["the method of lagrange multipliers is the economists workhorse for solving optimization problems",
           "the technique is a centerpiece of economic theory but unfortunately its usually taught poorly"]
vocab = fit(strings)    #the    
                        #{'the'}
                        #method
                        #{'the', 'method'}
                        #of...........
transform(strings,vocab)

In [99]:
def transform(dataset,vocab):
    rows=[]
    columns= []
    values = []
    if isinstance(dataset ,(list,)):
        for idx,row in enumerate(tqdm(dataset)):
            
            word_freq = dict(Counter(row.split())) # it gives keys and values
            for word,freq in word_freq.items():  # each unique word and frequency
                if len(word) < 2:
                    continue
                col_index = vocab.get(word,-1)
                if col_index != -1:
                    rows.append(idx)
                    columns.append(col_index)
                    values.append(freq)
        return csr_matrix((values , (rows,columns)), shape = (len(dataset),len(vocab)) )
strings = ["the method of lagrange multipliers is the economists workhorse for solving optimization problems",
           "the technique is a centerpiece of economic theory but unfortunately its usually taught poorly"]
vocab = fit(strings)
print('VOCAB :',vocab)
print('='*100)
print('VOCAB kEYS:',list(vocab.keys()))
print('='*100)
print('Sparse Matrix',transform(strings, vocab).toarray())
print('='*100)
print(transform(strings,vocab))
                
        

VOCAB : {'but': 0, 'centerpiece': 1, 'economic': 2, 'economists': 3, 'for': 4, 'is': 5, 'its': 6, 'lagrange': 7, 'method': 8, 'multipliers': 9, 'of': 10, 'optimization': 11, 'poorly': 12, 'problems': 13, 'solving': 14, 'taught': 15, 'technique': 16, 'the': 17, 'theory': 18, 'unfortunately': 19, 'usually': 20, 'workhorse': 21}
VOCAB kEYS: ['but', 'centerpiece', 'economic', 'economists', 'for', 'is', 'its', 'lagrange', 'method', 'multipliers', 'of', 'optimization', 'poorly', 'problems', 'solving', 'taught', 'technique', 'the', 'theory', 'unfortunately', 'usually', 'workhorse']



100%|██████████| 2/2 [00:00<?, ?it/s]


Sparse Matrix [[0 0 0 1 1 1 0 1 1 1 1 1 0 1 1 0 0 2 0 0 0 1]
 [1 1 1 0 0 1 1 0 0 0 1 0 1 0 0 1 1 1 1 1 1 0]]



100%|██████████| 2/2 [00:00<?, ?it/s]


  (0, 3)	1
  (0, 4)	1
  (0, 5)	1
  (0, 7)	1
  (0, 8)	1
  (0, 9)	1
  (0, 10)	1
  (0, 11)	1
  (0, 13)	1
  (0, 14)	1
  (0, 17)	2
  (0, 21)	1
  (1, 0)	1
  (1, 1)	1
  (1, 2)	1
  (1, 5)	1
  (1, 6)	1
  (1, 10)	1
  (1, 12)	1
  (1, 15)	1
  (1, 16)	1
  (1, 17)	1
  (1, 18)	1
  (1, 19)	1
  (1, 20)	1


## Comparing results with countvectorizer

In [100]:
from sklearn.feature_extraction.text import CountVectorizer
vec = CountVectorizer(analyzer='word')

vec.fit(strings)
feature_matrix_2 = vec.transform(strings)
print(feature_matrix_2.toarray())

[[0 0 0 1 1 1 0 1 1 1 1 1 0 1 1 0 0 2 0 0 0 1]
 [1 1 1 0 0 1 1 0 0 0 1 0 1 0 0 1 1 1 1 1 1 0]]


In [194]:
## SkLearn# Collection of string documents

corpus = [
     'this is the first document',
     'this document is the second document',
     'and this is the third one',
     'is this the first document',
]

## SkLearn Implementation

In [192]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
vectorizer.fit(corpus)
skl_output = vectorizer.transform(corpus)

In [193]:
# sklearn feature names, they are sorted in alphabetic order by default.

print(vectorizer.get_feature_names())

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']


In [195]:
# Here we will print the sklearn tfidf vectorizer idf values after applying the fit method
# After using the fit function on the corpus the vocab has 9 words in it, and each has its idf value.

print(vectorizer.idf_)

[1.91629073 1.22314355 1.51082562 1.         1.91629073 1.91629073
 1.         1.91629073 1.        ]


In [197]:
# shape of sklearn tfidf vectorizer output after applying transform method.

skl_output.shape

(4, 9)

In [196]:
# sklearn tfidf values for first line of the above corpus.
# Here the output is a sparse matrix

print(skl_output[0])

  (0, 8)	0.38408524091481483
  (0, 6)	0.38408524091481483
  (0, 3)	0.38408524091481483
  (0, 2)	0.5802858236844359
  (0, 1)	0.46979138557992045


In [114]:
# sklearn tfidf values for first line of the above corpus.
# To understand the output better, here we are converting the sparse output matrix to dense matrix and printing it.
# Notice that this output is normalized using L2 normalization. sklearn does this by default.

print(skl_output[0].toarray())

[[0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]]


## Custom Implementation

In [181]:
from collections import Counter
from tqdm import tqdm
from scipy.sparse import csr_matrix
import math
import operator
from sklearn.preprocessing import normalize
import numpy

def fit(corpus):
    unique_words = set()
    for row in corpus:
        for word in row.split():
            if len(word) < 2:
                continue
            unique_words.add(word)
    unique_words = sorted(list(unique_words))
    vocab = {j:i for i,j in enumerate(unique_words)}
    return vocab
                
vocab = fit(corpus)
#print(vocab)    #{'and': 0, 'document': 1, 'first': 2, 'is': 3, 'one': 4, 'second': 5, 'the': 6, 'third': 7, 'this': 8}

def idf(corpus,vocab):
    idf_dict = {}
    for word in vocab:
        count = 0
        for row in corpus:
            if word in row.split(' '):
                count +=1
        idf_dict[word] = 1 + (math.log((1+len(corpus))/(count+1))) 
    return idf_dict
idf_values = idf(corpus,vocab)
#print(idf_values) #{'and': 1.916290731874155, 'document': 1.2231435513142097, 'first': 1.5108256237659907, 'is': 1.0, 'one': 1.916290731874155, 'second': 1.916290731874155, 'the': 1.0, 'third': 1.916290731874155, 'this': 1.0}

def transform(corpus,vocab,idf_values):
    sparse_matrix = csr_matrix((len(corpus),len(vocab)))
    for row in range(0,len(corpus)):
        number_of_words_in_sentence = dict(Counter(corpus[row].split()))
        #print(number_of_words_in_sentence)
        #print(corpus[row].split())
        for word in corpus[row].split():
            if word in list(vocab.keys()):
                tf_idf_value = (number_of_words_in_sentence[word] / len(corpus[row].split()))*(idf_values[word])
                #print(tf_idf_value) # it gives tf_idf_values for all the reviews in the dataset
                sparse_matrix[row,vocab[word]] = tf_idf_value
                #print( sparse_matrix[row,vocab[word]] ) # it gives tf_idf_values for all the reviews in the dataset
    print(normalize(sparse_matrix,norm='l2',axis=1,copy=True,return_norm = False))
    output = normalize(sparse_matrix,norm='l2',axis=1,copy=True,return_norm = False)
    return output
final_output = transform(corpus,vocab,idf_values)
print(final_output)

  (0, 1)	0.4697913855799205
  (0, 2)	0.580285823684436
  (0, 3)	0.3840852409148149
  (0, 6)	0.3840852409148149
  (0, 8)	0.3840852409148149
  (1, 1)	0.6876235979836937
  (1, 3)	0.2810886740337529
  (1, 5)	0.5386476208856762
  (1, 6)	0.2810886740337529
  (1, 8)	0.2810886740337529
  (2, 0)	0.511848512707169
  (2, 3)	0.267103787642168
  (2, 4)	0.511848512707169
  (2, 6)	0.267103787642168
  (2, 7)	0.511848512707169
  (2, 8)	0.267103787642168
  (3, 1)	0.4697913855799205
  (3, 2)	0.580285823684436
  (3, 3)	0.3840852409148149
  (3, 6)	0.3840852409148149
  (3, 8)	0.3840852409148149
  (0, 1)	0.4697913855799205
  (0, 2)	0.580285823684436
  (0, 3)	0.3840852409148149
  (0, 6)	0.3840852409148149
  (0, 8)	0.3840852409148149
  (1, 1)	0.6876235979836937
  (1, 3)	0.2810886740337529
  (1, 5)	0.5386476208856762
  (1, 6)	0.2810886740337529
  (1, 8)	0.2810886740337529
  (2, 0)	0.511848512707169
  (2, 3)	0.267103787642168
  (2, 4)	0.511848512707169
  (2, 6)	0.267103787642168
  (2, 7)	0.511848512707169
  (2, 

In [222]:
from collections import Counter
from tqdm import tqdm
from scipy.sparse import csr_matrix
import math
import operator
from sklearn.preprocessing import normalize
import numpy

def IDF(corpus,unique_words):
    idf_dict = {}
    for word in unique_words:
        count = 0
        for row in corpus:
            if word in row:
                count += 1
            continue
        idf = 1 + (math.log((1+len(corpus))/(count+1))) 
    idf_dict.append(idf)
    return idf_dict

def fit(corpus):
    unique_words = set()
    for row in corpus:
        for word in row.split():
            if len(word) < 2:
                continue
            unique_words.add(word)
    unique_words = sorted(list(unique_words))
    vocab = {j:i for i,j in enumerate(unique_words)}
    return vocab
vocab = fit(corpus)
print(vocab)

def transform(corpus,vocab):
    rows = []
    columns = []
    values = []
    if isinstance(corpus,(list,)):
        for idx,row in enumerate(tqdm(corpus)):
            word_freq = dict(Counter(row.split()))
            #print(word_freq)
            for word,freq in word_freq.items():
                if len(word) < 2:
                    continue
                col_index = vocab.get(word, -1)
                if col_index != -1:
                    rows.append(idx)
                    columns.append(col_index)
                    tf = freq / len(row.split()) # term_frequency 
                    #𝑇𝐹(𝑡)=Number of times term t appears in a document / Total number of terms in the document/row.
                    idf_ =  vocab[word]
                    #𝐼𝐷𝐹(𝑡)=1+log𝑒[1 + Total number of documents in collection / 1+Number of documents with term t in it].
                    values.append((tf) * (idf_))
        g = normalize(csr_matrix((values, (rows,columns)), shape=(len(corpus),len(vocab))),norm='l2',axis=1,copy = True,return_norm= False)
        print(vocab)
        return g
    else:
        print("you need to pass list of strings")
    
final_output = transform(corpus,vocab)  
print(final_output)

{'and': 0, 'document': 1, 'first': 2, 'is': 3, 'one': 4, 'second': 5, 'the': 6, 'third': 7, 'this': 8}



100%|██████████| 4/4 [00:00<?, ?it/s]


{'and': 0, 'document': 1, 'first': 2, 'is': 3, 'one': 4, 'second': 5, 'the': 6, 'third': 7, 'this': 8}
  (0, 1)	0.0936585811581694
  (0, 2)	0.1873171623163388
  (0, 3)	0.2809757434745082
  (0, 6)	0.5619514869490164
  (0, 8)	0.7492686492653552
  (1, 1)	0.17025130615174972
  (1, 3)	0.2553769592276246
  (1, 5)	0.42562826537937426
  (1, 6)	0.5107539184552492
  (1, 8)	0.6810052246069989
  (2, 0)	0.0
  (2, 3)	0.22742941307367104
  (2, 4)	0.30323921743156135
  (2, 6)	0.4548588261473421
  (2, 7)	0.5306686305052324
  (2, 8)	0.6064784348631227
  (3, 1)	0.0936585811581694
  (3, 2)	0.1873171623163388
  (3, 3)	0.2809757434745082
  (3, 6)	0.5619514869490164
  (3, 8)	0.7492686492653552


In [223]:
# Below is the code to load the cleaned_strings pickle file provided
# Here corpus is of list type

import pickle
with open('cleaned_strings', 'rb') as f:
    corpus = pickle.load(f)
    
# printing the length of the corpus loaded
print("Number of documents in corpus = ",len(corpus))

Number of documents in corpus =  746


## SkLearn Implementation

In [225]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
vectorizer.fit(corpus)
skl_output = vectorizer.transform(corpus)

In [230]:
# sklearn feature names, they are sorted in alphabetic order by default.

print(vectorizer.get_feature_names()[0:50])

['aailiyah', 'abandoned', 'ability', 'abroad', 'absolutely', 'abstruse', 'abysmal', 'academy', 'accents', 'accessible', 'acclaimed', 'accolades', 'accurate', 'accurately', 'accused', 'achievement', 'achille', 'ackerman', 'act', 'acted', 'acting', 'action', 'actions', 'actor', 'actors', 'actress', 'actresses', 'actually', 'adams', 'adaptation', 'add', 'added', 'addition', 'admins', 'admiration', 'admitted', 'adorable', 'adrift', 'adventure', 'advise', 'aerial', 'aesthetically', 'affected', 'affleck', 'afraid', 'africa', 'afternoon', 'age', 'aged', 'ages']


In [234]:
# Here we will print the sklearn tfidf vectorizer idf values after applying the fit method
# After using the fit function on the corpus the vocab has 9 words in it, and each has its idf value.

print(vectorizer.idf_)

[6.922918   6.922918   6.22977082 ... 6.922918   6.5174529  6.922918  ]


In [235]:
# shape of sklearn tfidf vectorizer output after applying transform method.

skl_output.shape

(746, 2886)

In [236]:
# sklearn tfidf values for first line of the above corpus.
# Here the output is a sparse matrix

print(skl_output[0])

  (0, 2878)	0.35781145622317734
  (0, 2287)	0.3377679916467555
  (0, 1653)	0.35781145622317734
  (0, 1651)	0.16192317905848022
  (0, 1545)	0.30566026894803877
  (0, 720)	0.4123943870778812
  (0, 688)	0.4123943870778812
  (0, 53)	0.4123943870778812


In [237]:
# sklearn tfidf values for first line of the above corpus.
# To understand the output better, here we are converting the sparse output matrix to dense matrix and printing it.
# Notice that this output is normalized using L2 normalization. sklearn does this by default.

print(skl_output[0].toarray())

[[0. 0. 0. ... 0. 0. 0.]]


In [325]:
from collections import Counter
from tqdm import tqdm
from scipy.sparse import csr_matrix
import math
import operator
from sklearn.preprocessing import normalize
import numpy


def fit(corpus):
    unique_words = set()
    for row in corpus:
        #print(row)
        for word in row.split(' '):
            #print(word)
            if len(word) < 2:
                continue
            unique_words.add(word)
    unique_words = sorted(list(unique_words))
    vocab = {j:i for i,j in enumerate(unique_words)}
    return vocab
                
vocab = fit(corpus)
#print(vocab)

def IDF(corpus,vocab):
    idf_dict = {}
    idf_50 = []
    dic = {}
    for word in vocab:
        count = 0
        for row in corpus:
            if word in row.split(' '):
                count += 1
        idf_dict[word] = 1 + (math.log((1+len(corpus))/(count+1)))
    #print(idf_dict.items())
    idf_50 = sorted(idf_dict.items(),reverse = True , key = lambda x:x[1]) 
    idf_50 = idf_50[:50]
    dic = dict(idf_50)
    return dic
idf_values = IDF(corpus,vocab)
print(idf_values)            

def transform(corpus,idf_values):
    sparse_matrix = csr_matrix((len(corpus),len(idf_values)))
    l1 = []
    l2 = []
    for key in idf_values.keys():
        l1.append(key)
    for row in range(0,len(corpus)):
        number_of_words_in_sentence = dict(Counter(corpus[row].split()))
        for word in corpus[row].split():
            if word in list(idf_values.keys()):
                l2 = {j:i for i,j in enumerate(l1)}
                col_index = l2.get(word,-1)
                if col_index != -1:
                    tf_idf_value = (number_of_words_in_sentence[word] / len(corpus[row].split()))*(idf_values[word])
                    sparse_matrix[row,col_index] = tf_idf_value
    #print(normalize(sparse_matrix,norm='l2',axis=1,copy=True,return_norm = False))
    output = normalize(sparse_matrix,norm='l2',axis=1,copy=True,return_norm = False)
    return output
            #print(l2)
final_output = transform(corpus,idf_values)
print(final_output)

{'aailiyah': 6.922918004572872, 'abandoned': 6.922918004572872, 'abroad': 6.922918004572872, 'abstruse': 6.922918004572872, 'academy': 6.922918004572872, 'accents': 6.922918004572872, 'accessible': 6.922918004572872, 'acclaimed': 6.922918004572872, 'accolades': 6.922918004572872, 'accurate': 6.922918004572872, 'accurately': 6.922918004572872, 'achille': 6.922918004572872, 'ackerman': 6.922918004572872, 'actions': 6.922918004572872, 'adams': 6.922918004572872, 'add': 6.922918004572872, 'added': 6.922918004572872, 'admins': 6.922918004572872, 'admiration': 6.922918004572872, 'admitted': 6.922918004572872, 'adrift': 6.922918004572872, 'adventure': 6.922918004572872, 'aesthetically': 6.922918004572872, 'affected': 6.922918004572872, 'affleck': 6.922918004572872, 'afternoon': 6.922918004572872, 'aged': 6.922918004572872, 'ages': 6.922918004572872, 'agree': 6.922918004572872, 'agreed': 6.922918004572872, 'aimless': 6.922918004572872, 'aired': 6.922918004572872, 'akasha': 6.922918004572872, '

In [327]:
from sklearn.feature_extraction.text import CountVectorizer
vec = CountVectorizer(analyzer='word')

vec.fit(corpus)
feature_matrix_2 = vec.transform(corpus)
print(feature_matrix_2.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [316]:
# sklearn implementation
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
vectorizer.fit(corpus)
skl_output = vectorizer.transform(corpus)

topn_ids = np.argsort(vectorizer.idf_)[::-1]
features = vectorizer.get_feature_names()
top_n = 50
top_feats = [(features[i],vectorizer.idf_[i]) for i in topn_ids[:top_n]]  # topfeatures = features,tfidf values and iterates till 25
df = pd.DataFrame(top_feats)              # creating a dataframe of top_feats
df.columns = ['feature','tfidf']          # creating the columns
print(df)


def top_tfidf_features(row, features, top_n=200):
    # get top n tfidf values in row and return them with their corresponding ranks
    topn_ids = np.argsort(row)[::-1][:top_n]#sorting the top 25 in descending order of review given in calling function, till 25
    #np.argsort(row)[::-1] # sorting the row according to given in calling function[which review/row from descending order]
    #np.argsort(row)[::-1][:top_n] == it sort the row till 25 values
    top_feats = [(features[i],row[i]) for i in topn_ids]  # topfeatures = features,tfidf values and iterates till 25
    df = pd.DataFrame(top_feats)              # creating a dataframe of top_feats
    df.columns = ['feature','tfidf']          # creating the columns
    return df

top_tfidf = top_tfidf_features(final_output[0,:].toarray()[0],features,200)

# row = i had get the review 1 and converted into sparse matrix 


         feature     tfidf
0        zombiez  6.922918
1      havilland  6.922918
2         hearts  6.922918
3          heads  6.922918
4            hbo  6.922918
5       hayworth  6.922918
6          hayao  6.922918
7            hay  6.922918
8         hatred  6.922918
9          heche  6.922918
10        harris  6.922918
11         happy  6.922918
12     happiness  6.922918
13         hanks  6.922918
14       hankies  6.922918
15          hang  6.922918
16  heartwarming  6.922918
17         heels  6.922918
18          gone  6.922918
19          hero  6.922918
20        higher  6.922918
21          hide  6.922918
22           hes  6.922918
23       heroism  6.922918
24       heroine  6.922918
25        heroes  6.922918
26     hernandez  6.922918
27         heist  6.922918
28    hendrikson  6.922918
29       helping  6.922918
30          help  6.922918
31         helms  6.922918
32       hellish  6.922918
33         helen  6.922918
34       handles  6.922918
35        handle  6.922918
3

In [290]:


tf_idf_vect = TfidfVectorizer(ngram_range=(1,2))  # (unigram, bigram)
final_tf_idf = tf_idf_vect.fit_transform(corpus)

# final_tf_idf itslef is a sparse matirx

In [291]:
final_tf_idf.get_shape()
#during bow we had 115k dimensions[uni-gram] now we have 2.9M dimensions [massive]

#2.9M features/dimensions

(746, 9290)

In [292]:
features = tf_idf_vect.get_feature_names()
len(features)

9290

In [294]:
features[0:10]   #bi grams

['aailiyah',
 'aailiyah pretty',
 'abandoned',
 'abandoned factory',
 'ability',
 'ability dwight',
 'ability meld',
 'ability pull',
 'abroad',
 'abroad interacting']

In [295]:
# convert a row in sparsematrix to a numpy array
# for review3 if i wanna get the vector
print(final_tf_idf[3,:].toarray()[0])   #if want to get review 3 into sparse matrix

[0. 0. 0. ... 0. 0. 0.]


In [323]:
def top_tfidf_features(row, features, top_n=25):
    # get top n tfidf values in row and return them with their corresponding ranks
    topn_ids = np.argsort(row)[::-1][:top_n]#sorting the top 25 in descending order of review given in calling function, till 25
    #np.argsort(row)[::-1] # sorting the row according to given in calling function[which review/row from descending order]
    #np.argsort(row)[::-1][:top_n] == it sort the row till 25 values
    top_feats = [(features[i],row[i]) for i in topn_ids]  # topfeatures = features,tfidf values and iterates till 25
    df = pd.DataFrame(top_feats)              # creating a dataframe of top_feats
    df.columns = ['feature','tfidf']          # creating the columns
    return df

top_tfidf = top_tfidf_features(final_output[0,:].toarray()[0],features,25)

# row = i had get the review 1 and converted into sparse matrix 


In [324]:
print(top_tfidf)

        feature  tfidf
0           add    1.0
1          ages    0.0
2      accurate    0.0
3        action    0.0
4        acting    0.0
5         acted    0.0
6           act    0.0
7      ackerman    0.0
8       achille    0.0
9   achievement    0.0
10      accused    0.0
11   accurately    0.0
12    accolades    0.0
13        actor    0.0
14    acclaimed    0.0
15   accessible    0.0
16      accents    0.0
17      academy    0.0
18      abysmal    0.0
19     abstruse    0.0
20   absolutely    0.0
21       abroad    0.0
22      ability    0.0
23    abandoned    0.0
24      actions    0.0
